# -*- coding: utf-8 -*-
"""configuration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198M9BgtZBrSEzOYwc0hBQHHuyGTOb7sy
"""

import os

HOST = "10.0.2.15"
PORT = 80
WORKING_DIR = os.getcwd()
REQUEST_SIZE = 25240